### ISSUE TITLE
Spoke sync should dedupe cell records

### ISSUE THREAD

**Issue by deasterdaywfp** [WorkingFamilies/votivate#75]
**Environment:**
 - OS (Windows, Mac, etc): ALL
 - Browser (web) or Device (mobile): ALL

**Detailed Description**

Moving a targeted list, in this case, targets in Charleston, SC to a Spoke campaign results in one contact receiving multiple messages with different names assumed for them. Upon inspection of the DB, it shows all buggy convos had a dupe cell record elsewhere in the list

**Does It Have a Workaround?**

No, devastating to the campaign. 

**Screenshots**

See wfp4themany.slack.com #text4resistance for screenshots.

**Comment by deasterdaywfp** [comment]
@codygordon

**Comment by codygordon** [comment]
One piece we didn't really touch on that we should have caught! Changing this to a feature request. – will prioritize though. 

The issue here is that the TS cell matches will match folks in a household to the cell, so multiple people will have the same number attached to them. 

I see now that when you export and upload this universe (`Event Turnout: Criminal Justice Next Steps`) directly in the Spoke UI there is a "dumb" de-dupe done on the list validation (https://github.com/MoveOnOrg/Spoke/blob/a99b5bf765a158637c2de31887abfe9458654d78/src/lib/index.js#L60). I bet this hasn't come up because dupes are likely rarer on highly targeted universes, but in this instance it looks like there wasn't much filtering.

Anyway, we can try slightly better – Votivate can send the de-duped list using the person with the highest `mobile confidence score`, then it'll just sort by name I guess (seems like any secondary selection would be arbitrary, except maybe age?). This could help with the issue of people telling texts "oh, Bob is actually my dad" or whatever (cc @rbrtmnz).

**Comment by codygordon** [comment]
This is deployed to production. The counts will now display the number de-duped (including the count of bad numbers removed as well!)

Let me know if it works / if there are issues.

**Comment by rbrtmnz** [comment]
Where am I looking for the updated counts? Will they only appear in places where we have collected results since the sync started?

**Comment by codygordon** [comment]
This is just for new lists being sent to Spoke campaigns moving forward. The de-duping is done as the list is being sent and the counts are displayed in the modal upon a successful sync from the targeting universe (total synced to campaign minus dupes, opt-outs, and previously marked bad numbers).

**Comment by deasterdaywfp** [comment]
Thank you both for getting this fix in and deployed so quickly

*Dylan Easterday*
*National Volunteer Manager, Digital - Working Families Party*
*Working Families <http://workingfamilies.org>*
*Text *(347) 460-9451 or Schedule https://calendly.com/deasterday
Email deasterday@workingfamilies.org
Done with email? me too - join me here <http://bit.ly/WFP4theMany>

**Comment by rbrtmnz** [comment]
This is only pushing canvass results back to Votivate but not IDs or Tags, right?

**Comment by codygordon** [comment]
This issue isn't for sending results back to Votivate, re-read the comments. It's for picking one person to assign a mobile number to when multiple members of a hh are in a universe upon sending to Spoke as TS essentially assigns mobile numbers to households, not individuals. 

Right now, only bad numbers are synced back to Votivate so they aren't send back to Spoke. Still need to figure out how you want to sync results, if at all. Feel free to open a new feature request for that if you have a desire / path forward.
